server:
  port: 9093
spring:
  application:
    name: zuul-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9761/eureka

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    organization-service:
      path: /organization/**
      service-id: organization-service
    licensing-service: 
      path: /licensing/**
      service-id: licensing-service
